### ISSUE TITLE
Document.ProjectParameters node has no results (error with units)

### ISSUE THREAD

**Issue by Julie-Kidder** [andydandy74/ClockworkForDynamo#332]
**Describe the bug**
When using clockwork with Revit 2022 (Dynamo 2.10 and 2.12) the Document.ProjectParameters node returns only nulls.  
![Null Return](https://user-images.githubusercontent.com/92128368/136621915-a4ad509c-cddc-4814-9e30-784bc92dc663.PNG)
When I open the node, extract the python code and run directly I get the error: 

Warning: IronPythonEvaluator.EvaluateIronPythonScript operation failed. 
Traceback (most recent call last):
  File "<string>", line 41, in <module>
AttributeError: 'InternalDefinition' object has no attribute 'UnitType'

Editing the python script to remove all references to the unit type resolves and returns the expected outputs.  Ziped file attached showing null output and script with the clockwork node, original node python code, and edited code removing the units (workaround to resolve the error enough get what I needed for a script))

**Steps to Reproduce**
Try to use the Document.ProjectParameters node to get project parameter information

**Expected behavior**
Returning all the outputs 
of the node (or at least the ones that don't have an error)

**My setup**
- Operating System: Windows 10 20H2 19042.1237
- Dynamo version: 2.12.0.5650
- Clockwork version: Clockwork for Dynamo 2.x 2.3.0
- Revit version: 2022.1

**Housekeeping**
Please **make sure these boxes are checked** before submitting your issue:
- [ x] I am running a *supported* Clockwork version
- [ x] I am running the *latest available* Clockwork version
- [x ] My installed version of Clockwork matches the Dynamo version it's installed for
- [x ] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [ x] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser
[Clockwork Project Parameter.zip](https://github.com/andydandy74/ClockworkForDynamo/files/7314048/Clockwork.Project.Parameter.zip)
)

**Comment by Julie-Kidder** [comment]
Yes, it seems to be - I must have missed it when looking through the issues to see if it was already logged.

**Comment by andydandy74** [comment]
@Julie-Kidder  This is fixed for Revit 2022 with the latest commit. It will be in the next Clockwork update which (at the snail speed I'm going) might still be a while. Probably best if you download the changed nodes and replace them in your package directory.
